steps:
  - label: ":maven: Build and Deploy"
    command:
      - mvn -P release help:effective-pom -DforceStdout | sed -n '/maven-deploy-plugin/,/<\/plugin>/p'
      - mvn -P release -DskipTests -Dmaven.deploy.skip=true clean deploy
      - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - echo "Tagging release ${VERSION}"
      - git config user.name "Buildkite CI"
      - git config user.email "ci@mapsmessaging.io"
      - git tag -a "${VERSION}" -m "Release ${VERSION}"
      - git push origin "${VERSION}"
    agents:
      queue: "java_build_queue"

